### ISSUE TITLE
URL listener - Issue if file

### ISSUE THREAD

**Issue by jamesweech** [aripalo/node-irc-bot#1]
If I paste in a file URL: (e.g http://i.imgur.com/yiNa01J.jpg ) in the chat i get 

`/home/ircbot/node-irc-bot/node_modules/irc/lib/irc.js:748
                        throw err;
                              ^
SyntaxError: Invalid regular expression: /(https?:\/\/[^\s]+/: Unterminated group
    at new RegExp (<anonymous>)
    at urlify (/home/ircbot/node-irc-bot/observers/url.js:19:5)
    at module.exports (/home/ircbot/node-irc-bot/observers/url.js:49:15)
    at /home/ircbot/node-irc-bot/modules/observer-handler.js:17:51
    at Array.forEach (native)
    at module.exports (/home/ircbot/node-irc-bot/modules/observer-handler.js:16:36)
    at Client.<anonymous> (/home/ircbot/node-irc-bot/index.js:47:3)
    at Client.EventEmitter.emit (events.js:106:17)
    at Client.<anonymous> (/home/ircbot/node-irc-bot/node_modules/irc/lib/irc.js:517:22)
    at Client.EventEmitter.emit (events.js:95:17)
`

**Comment by cbcercas** [comment]
Fixed in https://github.com/aripalo/node-irc-bot/pull/2
You can close

**Comment by jamesweech** [comment]
Thanks
